# Boilerplate code generated by OVITO Pro 3.16.0
from ovito.data import *
from ovito.io import *
from ovito.modifiers import *
from ovito.pipeline import *
from ovito.qt_compat import QtCore
from ovito.vis import *

# ==== Set up pipeline ==== #

# Data import:
pipeline = import_file(
    "https://raw.githubusercontent.com/OpenDiS/OpenDiS/refs/heads/main/examples/11_restart_calculation/output_fcc_Cu_15um_1e3/restart.1000.exadis"
)


# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.particles_.particle_types_.type_by_id_(1).radius = 50.9430783522


pipeline.modifiers.append(modify_pipeline_input)

# ======= Set up visual elements ======= #

# Configure visual elements for pipeline
pipeline.compute().lines["Dislocations"].vis.width = 101.886156704
pipeline.compute().lines["Dislocations"].vis.color = [0.78, 0.5, 0.2]
pipeline.compute().lines["Dislocations"].vis.flat_shading = False
pipeline.compute().lines["Dislocations"].vis.wrapped_lines = True

# Add pipelines to visualization scene
pipeline.add_to_scene()

# ========== Set up rendering ========== #

# Viewport setup:
vp = Viewport(
    type=Viewport.Type.Ortho,
    fov=41053.3399827,
    camera_dir=[-0.4930973829529637, 0.8654224762860105, -0.08887580359089806],
    camera_pos=[-1.4540075827389956, -1.8743645810282032, -0.9874677488805901],
    camera_up=[-0.043998540892793286, 0.07722070229694292, 0.9960427157185942],
)

# Rendering:
vp.render_image(filename="image.png", size=(800, 800))
