# Boilerplate code generated by OVITO Pro 3.11.0
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore


# ==== Set up pipeline ==== #

# Data import:
pipeline = import_file(
    "https://raw.githubusercontent.com/OpenDiS/OpenDiS/refs/heads/main/examples/10_strain_hardening/180chains_16.10e.data"
)


# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.particles_.particle_types_.type_by_id_(1).color = [
        1.0,
        0.6549019607843137,
        0.10196078431372549,
    ]
    data.particles_.particle_types_.type_by_id_(1).radius = 254.715391761


pipeline.modifiers.append(modify_pipeline_input)

# Color coding:
pipeline.modifiers.append(
    ColorCodingModifier(
        property="Normal vector.3",
        start_value=-0.57735026919,
        end_value=1.0,
        gradient=ColorCodingModifier.Viridis(),
        operate_on="lines:Arms",
    )
)

# ======= Set up visual elements ======= #

# Configure visual elements for pipeline
pipeline.compute().cell.vis.line_width = 200.0
pipeline.compute().particles.vis.enabled = False
pipeline.compute().lines["Arms"].vis.width = 509.430783522
pipeline.compute().lines["Arms"].vis.color = [
    1.0,
    0.6549019607843137,
    0.10196078431372549,
]
pipeline.compute().lines["Arms"].vis.shading = LinesVis.Shading.Normal
pipeline.compute().lines["Arms"].vis.wrapped_lines = True

# Add pipelines to scene
pipeline.add_to_scene()

# ========== Set up rendering ========== #

# Viewport setup:
vp = Viewport(
    type=Viewport.Type.Perspective,
    fov=0.610865238198,
    camera_dir=[0.5898716859872614, -0.6814919253105434, -0.43315141672061325],
    camera_pos=[-96967.7306464858, 113863.44552512806, 67393.4705559644],
)

# Renderer setup:
renderer = AnariRenderer()

# Rendering:
vp.render_image(filename="image.png", size=(1000, 1000), renderer=renderer)
