# Boilerplate code generated by OVITO Pro 3.16.0
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore


# ==== Set up pipeline ==== #

# Data import:
pipeline = import_file('https://raw.githubusercontent.com/OpenDiS/OpenDiS/refs/heads/main/examples/10_strain_hardening/180chains_16.10e.data')

# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.particles_.particle_types_.type_by_id_(1).radius = 50.9430783522
pipeline.modifiers.append(modify_pipeline_input)

# Color coding:
pipeline.modifiers.append(ColorCodingModifier(
    property = 'Normal vector.Z', 
    start_value = -1.0, 
    end_value = 1.0, 
    gradient = ColorCodingModifier.Viridis(), 
    operate_on = 'lines:Dislocations'))

# ======= Set up visual elements ======= #

# Configure visual elements for pipeline 
pipeline.compute().particles.vis.enabled = False
pipeline.compute().lines['Dislocations'].vis.width = 101.886156704
pipeline.compute().lines['Dislocations'].vis.color = [0.78, 0.5, 0.2]
pipeline.compute().lines['Dislocations'].vis.flat_shading = False
pipeline.compute().lines['Dislocations'].vis.wrapped_lines = True

# Add pipelines to visualization scene
pipeline.add_to_scene()

# ========== Set up rendering ========== #

# Viewport setup:
vp = Viewport(
    type = Viewport.Type.Perspective, 
    fov = 0.610865238198, 
    camera_dir = [-0.3148341696294794, 0.8948955463196848, -0.31629322915754804], 
    camera_pos = [51017.98315701337, -145015.19897572053, 51256.63233278926], 
    camera_up = [-0.12814427648248453, 0.29011228171908426, 0.9483743503493373])

# Rendering:
vp.render_image(filename='image.png', size=(600, 600))